### ISSUE TITLE
Could you provide 3DScene result mesh or ckpt?

### ISSUE THREAD

**Issue by takeshie** [Ouasfi/SparseOcc#2]
Thank you for providing such an interesting work. I would like to compare the visualization of 3DScene, but I am unable to obtain the correct results. May I ask if you can provide relevant mesh or ckpt?

**Comment by takeshie** [comment]
I already slove this issue, thanks again for this work.

**Comment by Ouasfi** [comment]
Hi @takeshie, I added the meshes [here](https://drive.google.com/file/d/1R_OVSSyMKCD88pEIIuTnKB_MAE4Pa_PA/view?usp=sharing). Let me know if you are not able to reproduce them.

**Comment by takeshie** [comment]
> Hi @takeshie, I added the meshes [here](https://drive.google.com/file/d/1R_OVSSyMKCD88pEIIuTnKB_MAE4Pa_PA/view?usp=sharing). Let me know if you are not able to reproduce them.

get~ thanks for your kind reply

**Comment by pg131413** [comment]
> I already slove this issue, thanks again for this work.

Can you reproduce the experimental data of 3D scenes? If yes, please share the detailed procedures and methods for reproduction.
